version: "2"
services:
  prod:
    restart: always
    build: .
    hostname: "{{.Service.Name}}-{{.Task.Slot}}"
    command: npm run serve
    volumes:
      - /usr/local/daojam-prod/backend-config/config.local.js:/usr/src/app/config/config.default.js
      - /usr/local/daojam-prod/backend-config/apiaccesstoken.js:/usr/src/app/config/apiaccesstoken.js
    ports:
      - 7653:7001
    networks:
      overlay:
  
  test:
    restart: always
    build: .
    hostname: "{{.Service.Name}}-{{.Task.Slot}}"
    command: npm run dev
    volumes:
      - /usr/local/daojam-testing/backend-config/config.local.js:/usr/src/app/config/config.default.js
      - /usr/local/daojam-testing/backend-config/apiaccesstoken.js:/usr/src/app/config/apiaccesstoken.js
      - /usr/local/daojam-testing/backend-config/shellteo.json:/usr/src/neardev/default/shellteo.json
    ports:
      - 7652:7001
    networks:
      overlay:

  local:
    restart: always
    build: .
    hostname: "{{.Service.Name}}-{{.Task.Slot}}"
    # command: npm run serve
    command: npm run dev
    volumes:
      - /Users/zhangxiang/workspace/daojam-backend/config/config.default.js:/usr/src/app/config/config.default.js
      - /Users/zhangxiang/workspace/daojam-backend/config/apiaccesstoken.js:/usr/src/app/config/apiaccesstoken.js
    ports:
      - 7652:7001
    networks:
      overlay:

networks:
  overlay: